wage = float(input("Enter hourly wage rate: "))
rent = float(input("Enter rent: "))
internet = float(input("Enter internet bill: "))
groceries = float(input("Enter bill of groceries: "))
spending = float(input("Amount used for spending lesiurely: "))
working_hours = int(input("Number of hours worked in a day: "))
daily_wage = (wage * working_hours)
month_wage = (wage * working_hours * 4)
monthly_exp = (rent + internet + groceries + spending)
break_even = (monthly_exp // (wage * working_hours ))
extra = (100 // wage)
leftover_money = (month_wage - monthly_exp)
print("Amount earned in a day is $ ", daily_wage)
print("Amount earned in a month is $ ", month_wage)
print("Total monthly expense is $ ", monthly_exp)
print("Hours to break even is ", str(break_even) + "hours")
print("To earn an extra 100$ you need to work ", str(extra) + " more hours")
print("The amount of money left over for the month is $ ", leftover_money)